# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build_server:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile and Build
      run: mvn clean compile
      
    - name: Deploy
      run: mvn package
    
    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: Server
        path: server/target/*
        retention-days: 1
      
  
  build_client:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        check-latest: true
        
    - name: Install Yarn
      run: npm install yarn
      
    - name: Install modules
      run: npx yarn install
      
    - name: Build
      run: npx yarn build
      
    - name: Zip build
      run: zip -r client.zip build
      
    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: Client
        path: client/client.zip
        retention-days: 1
  
  
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [build_server, build_client]
    
    steps:
    - name: Get server artifact
      uses: actions/download-artifact@v3
      with:
        name: Server
        path: release
        
    - name: Get client artifact
      uses: actions/download-artifact@v3
      with:
        name: Client
        path: release
            
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        name: "Autolink ${{ github.event.inputs.version }}"
        tag_name: ${{ github.event.inputs.version }}
        files: |
          release/*
