# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build_server:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile and Build
      working-directory: server
      run: mvn clean compile
      
    - name: Deploy
      working-directory: server
      run: mvn package
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        name: "Autolink ${{ github.event.inputs.version }}"
        tag_name: ${{ github.event.inputs.version }}
        files: |
          server/target/project2*.jar
